### ISSUE TITLE
[Suggestion] Port over Mr. Okushama's NES emulator?

### ISSUE THREAD

**Issue by Techokami** [NPException42/NPArcade#7]
That was a big, popular thing. People liked the concept of playing NES games on the mod. Maybe it should be ported over? Or better yet, integrated as an optional core for game entries to use, as defined in the JSON? So you can have new games made with the Java API, and _legal homebrew_ (cough, cough) via the NES emulator core? Would make more sense than the frontend with a buttload of ROMs, IMHO.

**Comment by NPException** [comment]
I already asked Mr. Okushama if he would port his NES emulator over when I release the arcade mod, and he basically replied with what sounded like an optimistic "maybe" to me. :)

But I will in no way integrate the NES emulator straight into the mods code (again). This was how it was done in the old version of the mod and that was the thing that slowed me down in developing the mod. Because I did not understand what it did, and it was hardwired into many parts of the mod.

However, I am designing the current specification for arcade games in a way that allows them to run background threads if they want to (which was necessary for the NES emulator). And I am planning to have a seperate GitHub repo with a collection of curated games, that will be available to every mod user without having to download those games manually. And should oku port it over, it will definitely be in that list.
